# Generated by Django 3.2.13 on 2022-06-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='resume',
        ),
    ]
